Docker is working again

diff --git a/api/compiler/tmp/run b/api/compiler/tmp/run
--- a/api/compiler/tmp/run
+++ b/api/compiler/tmp/run
@@ -1,4 +1,9 @@
 #! /bin/bash
+if [[ $# < 3 ]] 
+then
+  echo "arguments required"
+  exit 1
+fi
 
 lang=$1
 files=()
